
image: magalixcorp/policy-agent:latest
namespace: policy-system 
failurePolicy: Ignore

# If you don't want to use cert-manager, set useCertManager to false and provide your own certs
useCertManager: true
certificate: ""
key: ""
caCertificate: ""

persistence:
  enabled: true
  claimStorage: 1Gi
  sinkDir: /tmp
  # storageClassName: standard

config:
  accountId: ""
  clusterId: ""
  admission:
    enabled: true
    sinks:
      fileSystemSink:
        filePath: "/tmp/result.json"
      k8sEventsSink:
        enabled: true

configFile: "/config/config.yaml"