
image: magalixcorp/policy-agent
failurePolicy: Ignore

# If you don't want to use cert-manager, set useCertManager to false and provide your own certs
useCertManager: true
certificate: ""
key: ""
caCertificate: ""

# Cert manager sub chart configuration set `install` to true to install cert manager
cert-manager:
  install: false

persistence:
  enabled: true
  claimStorage: 1Gi
  sinkDir: /tmp
  # storageClassName: standard

config:
  accountId: ""
  clusterId: ""
  admission:
    enabled: true
    sinks:
      fileSystemSink:
        filePath: "/tmp/result.json"
      k8sEventsSink:
        enabled: true
