
image: magalixcorp/policy-agent
failurePolicy: Ignore

# If you don't want to use cert-manager, set useCertManager to false and provide your own certs
useCertManager: true
certificate: ""
key: ""
caCertificate: ""

persistence:
  enabled: true
  claimStorage: 1Gi
  sinkDir: /tmp
  # storageClassName: standard

config:
  AGENT_FILESYSTEM_SINK_FILE_PATH: "/tmp/result.json"
  # Enable writing violations as K8s events
  AGENT_ENABLE_K8S_EVENTS_SINK: "true"
  # Enable pushing violations to flux notification controller
  # AGENT_FLUX_NOTIFICATION_SINK_ADDR: <flux-notification-controller-svc>

  # enbales admission functionality
  AGENT_ENABLE_ADMISSION: "1"

accountId: ""
clusterId: ""

# Cert manager sub chart configuration set `install` to true to install cert manager
cert-manager:
  install: false
