name: Build Changelog and Github Release

on:
  push:
    tags:
      - v*

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
          cache: true

      - name: Build binary
        run: |
          make build

      - name: Running ElasticSearch
        run: |
          docker run -itd --name elasticsearch -p 9200:9200 -e "discovery.type=single-node" -e "xpack.security.enabled=false" docker.elastic.co/elasticsearch/elasticsearch:8.3.3
          sleep 20
          timeout 120 sh -c 'until nc -z $0 $1; do echo "waiting for elasticsearch to start on port 9200"; sleep 5; done' localhost 9200

      - name: run test
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: |
          make test
          bash <(curl -s https://codecov.io/bash) -F unit

      - name: Build docker image
        run: |
          make image VERSION=${{  github.ref_name }}

      - name: Scan The Image
        run: |
          REPO=policy-agent
          VERSION=${{  github.ref_name }}

          echo scanning ${REPO}:${VERSION}
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin
          grype "${REPO}:${VERSION}" --scope all-layers > /tmp/report.txt #--fail-on high to fail on sev high

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Release and push to Docker Registry
        run: |
          make push@weaveworks tag-file=new-tag version-file=new-version VERSION=${{  github.ref_name }}

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: "${{ github.workspace }}/.github/workflows/changelog_configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
