name: Release Charts

on:
  pull_request:
    branches: [ master, dev, release-notes ]
  # workflow_run:
  #   workflows: ["build"]
  #   branches: [master, release-notes]
  #   types: 
  #     - completed

jobs:
  release:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: gh-pages
          ref: gh-pages
          fetch-depth: 0
      
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: "${{ github.workspace }}/.github/workflows/changelog_configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Release
        shell: bash
        run: |
          echo heyyyy ${{steps.build_changelog.outputs.changelog}}
          helm package master/helm
          mkdir -p gh-pages/releases
          mv policy-agent-* gh-pages/releases/
          cd gh-pages
          helm repo index releases --url https://weaveworks.github.io/policy-agent/releases
          mv releases/index.yaml index.yaml
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add releases index.yaml
          git commit -m "update release charts"
          git push
